"""The live loop: real electrodes -> reducer -> model -> the matrix.

Same shape as llm/filters/harness.py, which is the replay version of this
against synthetic data. The reduction layer and the prompts are imported from
there rather than reimplemented -- if the two ever disagree, the replay
harness stops being evidence about what the live loop does.

What is different from the harness:

  * the window comes off disk, from the CSV that gpio/adc.py writes, so the
    loop survives a restart and picks up mid-run instead of waiting 30 minutes
  * the action is applied to real hardware, or deliberately withheld
  * every turn is appended to a JSONL log whether or not anything happened

Sham blocks. Some fraction of turns are run with the action logged and not
applied. The model is never told which turn it is in -- that is the whole
point, and it is why `applied` lives in the log and never in the prompt. A
sham block is not an error path; it is the control.

    ./scripts/py llm/loop.py --check      # connectivity and window, no turns
    ./scripts/py llm/loop.py --dry-run    # full loop, never drives the matrix
    sudo ./scripts/py llm/loop.py         # live (the matrix needs root)

Testing without waiting on an organism. --replay slides the same loop along a
fixed session and --speed compresses the clock, so a 24-turn run that would
take four hours live takes under a minute. Replay always implies --dry-run.

    ./scripts/py llm/loop.py --replay synthetic --speed 600 --turns 24
    ./scripts/py llm/loop.py --replay data/readings/electrodes_20260805.csv --speed 600

Synthetic sessions carry a planted event at a known turn and log it alongside
the model's note, so a claim can be checked against whether anything happened.
A recording cannot do that -- you do not know what was in it -- but it is the
only way to see how the loop behaves on real noise. Use both.
"""

import argparse
import json
import os
import pathlib
import random
import signal
import sys
import time
from datetime import datetime, timezone

import requests

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / 'api'))
sys.path.insert(0, str(ROOT / 'gpio'))
sys.path.insert(0, str(HERE / 'filters'))

import syspath  # noqa: E402,F401  (path setup, must precede hardware imports)

import config  # noqa: E402
from reducer import reduce_window  # noqa: E402
from store import channels_from_rows, electrode_log  # noqa: E402

# The three prompt variants live in llm/filters/prompts.md as the source of
# truth. harness.py carries copies of BLIND and NULL; INFORMED is only in the
# markdown, so it is parsed out rather than duplicated a third time here.
PROMPTS_MD = HERE / 'filters' / 'prompts.md'


def load_prompts():
    """Parse the fenced prompt blocks out of prompts.md, keyed by heading."""
    prompts, current, in_block, buffer = {}, None, False, []
    for line in PROMPTS_MD.read_text(encoding='utf-8').splitlines():
        if line.startswith('## '):
            current = line[3:].strip().lower()
        elif line.startswith('```'):
            if in_block and current:
                prompts[current] = '\n'.join(buffer).strip()
                buffer = []
            in_block = not in_block
        elif in_block:
            buffer.append(line)
    return {k: v for k, v in prompts.items() if v}


class LiveSource:
    """Windows off the CSV that gpio/adc.py is writing right now."""

    label = "live"

    def __init__(self, config, window_s, channels):
        self.log = electrode_log(config)
        self.window_s = window_s
        self.channels = channels

    def describe(self):
        rows = self.log.recent(self.window_s)
        span = (float(rows[-1]['timestamp']) - float(rows[0]['timestamp'])
                if rows else 0.0)
        return f"{len(rows)} samples spanning {span / 60:.1f} min"

    def window(self, turn):
        return channels_from_rows(self.log.recent(self.window_s), self.channels)


class ReplaySource:
    """Windows slid along a fixed session, so a run can be tested in minutes.

    The point is to exercise this file -- the reduction, the validation, the
    sham draw, the logging -- without waiting on an organism that reconfigures
    over hours. Two sources:

      synthetic   generated by llm/filters/harness.py, with a planted event at
                  a known time, so anything else the model reports is its own
                  invention
      a CSV path  a previously recorded run out of data/readings

    Real recordings cannot tell you whether the model confabulated, because
    you do not know what was in them. Synthetic can. Use both.
    """

    def __init__(self, spec, window_s, interval_s, channels, sample_hz=1):
        self.window_s = window_s
        self.interval_s = interval_s
        self.channels = channels
        self.sample_hz = sample_hz

        if spec == 'synthetic':
            from harness import session

            # One planted event: the period lengthens 90s -> 140s across turns
            # 10 to 14. Nothing happens anywhere else in the session.
            start = window_s + 10 * interval_s
            self.events = [(start, start + 4 * interval_s, 'period_s', 140.0)]
            duration = window_s + 40 * interval_s
            raw = session(duration_s=duration, events=self.events,
                          n_channels=len(channels))
            self.series = {f'ch{c}': raw[f'ch{i}']
                           for i, c in enumerate(channels)}
            self.label = f"synthetic, event planted at turn 10-14"
        else:
            import csv as _csv

            path = pathlib.Path(spec)
            if not path.exists():
                raise FileNotFoundError(f"no such recording: {spec}")
            with open(path, newline='', encoding='utf-8') as handle:
                rows = list(_csv.DictReader(handle))
            self.series = channels_from_rows(rows, channels)
            self.events = []
            self.label = f"{path.name}, {len(rows)} samples"

        self.length = min((len(v) for v in self.series.values()), default=0)

    def describe(self):
        total = self.length / self.sample_hz
        turns = max(0, int((total - self.window_s) // self.interval_s))
        return f"{self.label}; {total / 60:.0f} min = {turns} turns"

    def window(self, turn):
        """The window ending `turn` intervals after the first full window."""
        end = int((self.window_s + turn * self.interval_s) * self.sample_hz)
        start = max(0, end - int(self.window_s * self.sample_hz))
        if end > self.length:
            return None
        return {name: values[start:end] for name, values in self.series.items()}

    def planted_at(self, turn):
        """Whether a planted event is active at this turn, for the log."""
        moment = self.window_s + turn * self.interval_s
        return [e for e in self.events
                if e[0] <= moment <= e[1] + self.interval_s]


class Ollama:
    """Chat client for the model running on the laptop."""

    def __init__(self, host, model, timeout=300):
        self.url = host.rstrip('/') + '/api/chat'
        self.model = model
        self.timeout = timeout

    def reachable(self):
        """(ok, detail). Checks the server answers and has the model."""
        tags = self.url.replace('/api/chat', '/api/tags')
        try:
            response = requests.get(tags, timeout=10)
            response.raise_for_status()
        except requests.RequestException as exc:
            return False, str(exc)

        names = [m.get('name', '') for m in response.json().get('models', [])]
        if not any(n == self.model or n.startswith(self.model + ':')
                   for n in names):
            return False, (f"{self.model} not pulled; available: "
                           f"{', '.join(names) or 'none'}")
        return True, f"{self.model} available"

    def ask(self, system, state, history, retries=2):
        messages = [{"role": "system", "content": system}]
        messages += history
        messages.append({"role": "user", "content": json.dumps(state)})

        last_error = None
        for attempt in range(retries + 1):
            response = requests.post(self.url, json={
                "model": self.model,
                "messages": messages,
                "stream": False,
                # Constrains sampling to valid JSON. Without it the model
                # occasionally emits a literal newline inside a string and
                # the parse fails, which loses the turn.
                "format": "json",
                # A retry at a lower temperature is a genuine second try
                # rather than the same dice roll again.
                "options": {"temperature": 0.8 if attempt == 0 else 0.3},
            }, timeout=self.timeout)
            response.raise_for_status()

            text = response.json()["message"]["content"]
            cleaned = text.replace("```json", "").replace("```", "").strip()
            try:
                return json.loads(cleaned)
            except json.JSONDecodeError as exc:
                last_error = exc
                try:
                    return json.loads(cleaned, strict=False)
                except json.JSONDecodeError:
                    pass

        raise ValueError(f"unparseable after {retries + 1} attempts: "
                         f"{last_error}\nraw: {cleaned[:400]}")


class TurnLog:
    """Append-only JSONL of every turn, sham or not.

    Replay and dry runs write to a `replay/` subdirectory rather than
    alongside the real record. Synthetic turns look exactly like live ones
    once they are in a file -- same shape, same fields, plausible numbers --
    and anything later reading data/logs to ask what the organism did must not
    have to guess which rows were about an organism at all.
    """

    def __init__(self, directory, replay=False):
        if replay:
            directory = os.path.join(directory, 'replay')
        os.makedirs(directory, exist_ok=True)
        self.directory = directory

    def append(self, record):
        day = datetime.now(timezone.utc).strftime('%Y%m%d')
        path = os.path.join(self.directory, f'turns_{day}.jsonl')
        with open(path, 'a', encoding='utf-8') as handle:
            handle.write(json.dumps(record) + '\n')
        return path


def validate_action(reply, zones, barrier_zone, max_duration):
    """Pull a usable light action out of the reply, or None.

    The model is asked for JSON but is not constrained to sensible values, so
    everything is bounded here rather than trusted. A refused action is still
    logged -- what the model asked for is data even when it is unusable.
    """
    light = reply.get('light')
    if not isinstance(light, dict):
        return None, "no light action"

    try:
        zone = int(light['zone'])
        intensity = float(light.get('intensity', 1.0))
        duration = float(light.get('duration_s', 60))
    except (KeyError, TypeError, ValueError) as exc:
        return None, f"malformed light action: {exc}"

    if zone == barrier_zone:
        return None, f"zone {zone} is the barrier and is not drivable"
    if not 0 <= zone < zones:
        return None, f"zone {zone} outside 0..{zones - 1}"

    return {
        "zone": zone,
        "intensity": min(max(intensity, 0.0), 1.0),
        "duration_s": min(max(duration, 0.0), max_duration),
    }, None


def open_matrix(dry_run):
    """The panel, preferring the root-owned daemon.

    With matrixd running this works unprivileged, so a live run no longer needs
    sudo. Without it, the direct fallback still opens the panel in-process,
    which needs both root and the system interpreter.
    """
    if dry_run:
        return None, "dry run"
    try:
        from matrix_client import open_matrix as _open

        return _open()
    except Exception as exc:
        return None, str(exc)


def install_signal_handlers():
    """Make SIGTERM unwind the stack instead of killing the process outright.

    systemd stops a service with SIGTERM, and Python's default action for it
    terminates immediately without running `finally` blocks. That matters here:
    the `finally` at the end of main() is what clears the stimulus. Without
    this, `systemctl stop sllm-loop` would leave whichever zone the model last
    chose lit indefinitely, with nothing left running that knows to turn it off.
    """
    def _interrupt(_sig, _frame):
        raise KeyboardInterrupt

    signal.signal(signal.SIGTERM, _interrupt)


def main():
    install_signal_handlers()
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true',
                        help='verify Ollama and the data window, run no turns')
    parser.add_argument('--dry-run', action='store_true',
                        help='run turns but never drive the matrix')
    parser.add_argument('--prompt', default=getattr(config, 'LLM_PROMPT', 'blind'))
    parser.add_argument('--turns', type=int, default=0, help='0 runs forever')
    parser.add_argument('--interval', type=int,
                        default=getattr(config, 'LLM_TURN_INTERVAL', 600))
    parser.add_argument('--host', default=getattr(config, 'OLLAMA_HOST', ''))
    parser.add_argument('--model', default=getattr(config, 'OLLAMA_MODEL', ''))
    parser.add_argument('--replay', metavar='SOURCE',
                        help="'synthetic', or a path to a recorded "
                             "data/readings/electrodes_*.csv")
    parser.add_argument('--speed', type=float, default=1.0,
                        help='time compression in replay, e.g. 600 runs a '
                             '10 min turn interval in 1 s')
    parser.add_argument('--sham-rate', type=float, default=None)
    args = parser.parse_args()

    window_s = getattr(config, 'LLM_WINDOW_S', 1800)
    history_turns = getattr(config, 'LLM_HISTORY_TURNS', 8)
    sham_rate = (args.sham_rate if args.sham_rate is not None
                 else getattr(config, 'LLM_SHAM_RATE', 0.25))
    channels = tuple(getattr(config, 'ADC_CHANNELS', (0, 1, 2)))

    # Replay implies dry run. Driving the panel from a recording would put
    # real light on the organism on the strength of data that is not about it.
    if args.replay:
        args.dry_run = True

    prompts = load_prompts()
    if args.prompt not in prompts:
        print(f"unknown prompt '{args.prompt}'; have {sorted(prompts)}")
        return 1
    system = prompts[args.prompt]

    ollama = Ollama(args.host, args.model)
    turns_log = TurnLog(config.LOG_DIR, replay=bool(args.replay) or args.dry_run)

    # Zone geometry comes from leds.py so there is one definition of how many
    # zones exist and which one is the barrier.
    import leds

    if args.replay:
        source = ReplaySource(args.replay, window_s, args.interval, channels)
    else:
        source = LiveSource(config, window_s, channels)

    print(f"model    {args.model} at {args.host}")
    ok, detail = ollama.reachable()
    print(f"ollama   {'OK' if ok else 'UNREACHABLE'}: {detail}")
    print(f"source   {source.describe()}")
    print(f"prompt   {args.prompt}")
    print(f"sham     {sham_rate:.0%} of turns")
    if args.replay:
        print(f"speed    {args.speed}x  (dry run: the matrix is never driven)")

    if args.check:
        return 0 if ok else 1
    if not ok:
        print("\nrefusing to start with the model unreachable")
        return 1

    matrix, matrix_error = open_matrix(args.dry_run)
    print(f"matrix   {'ready' if matrix else 'NOT DRIVEN (' + str(matrix_error) + ')'}")
    if matrix is None and not args.dry_run:
        print("\nActions will be logged but not applied. That is a permanent\n"
              "sham block, not an experiment -- fix the matrix first or pass\n"
              "--dry-run to say so deliberately.")
        return 1

    history, previous, turn = [], None, 0
    print(f"\nrunning, a turn every {args.interval}s. ctrl-c to stop.\n")

    try:
        while args.turns == 0 or turn < args.turns:
            started = time.monotonic()
            series = source.window(turn)

            if series is None:
                print(f"\nreplay exhausted after {turn} turns")
                break

            shortest = min((len(v) for v in series.values()), default=0)
            if shortest < window_s * 0.5:
                print(f"[turn {turn}] only {shortest}s of data, waiting")
                time.sleep(min(args.interval, 60))
                continue

            state = reduce_window(series, previous)
            previous = state

            record = {
                "turn": turn,
                "datetime": datetime.now(timezone.utc).astimezone().isoformat(),
                "prompt": args.prompt,
                "source": getattr(source, 'label', 'live'),
                "window_samples": shortest,
                "state": state,
            }
            if args.replay and hasattr(source, 'planted_at'):
                # What was actually in the data, so a note claiming an event
                # can be checked against whether one happened.
                record["events_planted"] = source.planted_at(turn)

            try:
                reply = ollama.ask(system, state, history[-history_turns * 2:])
            except Exception as exc:
                print(f"[turn {turn}] model failed: {exc}")
                record["error"] = str(exc)
                turns_log.append(record)
                turn += 1
                time.sleep(max(0, args.interval / args.speed - (time.monotonic() - started)))
                continue

            record["reply"] = reply

            action, refusal = validate_action(
                reply, leds.ZONES, leds.BARRIER_ZONE,
                getattr(config, 'MAX_STIMULUS_DURATION', 300))
            record["action_refused"] = refusal

            # Decided before the action is applied, and never revealed to the
            # model. The reply is already in hand either way, so a sham turn
            # costs exactly what a real one does.
            is_sham = random.random() < sham_rate
            record["sham"] = is_sham
            record["applied"] = False

            if action and not is_sham and not args.dry_run:
                try:
                    matrix.clear_stimulus()
                    matrix.set_zone(action["zone"], action["intensity"])
                    record["applied"] = True
                except Exception as exc:
                    record["apply_error"] = str(exc)
                    print(f"[turn {turn}] apply failed: {exc}")

            record["action"] = action
            path = turns_log.append(record)

            history.append({"role": "user", "content": json.dumps(state)})
            history.append({"role": "assistant", "content": json.dumps(reply)})

            stamp = datetime.now().strftime('%H:%M:%S')
            mark = "SHAM" if is_sham else ("applied" if record["applied"] else "--")
            zone = action["zone"] if action else "none"
            period = state.get(f'ch{channels[0]}', {}).get('period_s')
            planted = "  <-- planted" if record.get("events_planted") else ""
            print(f"[{stamp}] turn {turn}  period {period}s  "
                  f"zone {zone}  {mark}{planted}")
            if reply.get('resource'):
                # Placing an oat flake is a physical act nobody has automated.
                # Surfaced loudly so it can be honoured or deliberately not.
                print(f"           RESOURCE REQUESTED: {reply['resource']}")
            print(f"           {str(reply.get('note', ''))[:200]}")

            turn += 1
            # In replay --speed compresses this; live it is always 1.0.
            time.sleep(max(0, args.interval / args.speed - (time.monotonic() - started)))
    except KeyboardInterrupt:
        print("\nstopped")
    finally:
        if matrix is not None:
            matrix.clear_stimulus()
        print(f"turns logged under {turns_log.directory}")

    return 0


if __name__ == '__main__':
    sys.exit(main())
