"""Admin controls: start and stop the model loop from the web page.

This is the one part of the API that changes what the installation is doing,
reachable from the public internet, so the threat model is written down rather
than assumed.

**What an attacker gets if this falls:** the ability to start and stop
sllm-loop. Not a shell, not the matrix directly, not the data. The sudoers rule
in deploy/sllm-admin.sudoers permits exactly two argv vectors and nothing else,
so a compromise here does not escalate past toggling one service.

## Authentication is a passkey (WebAuthn), not a password

There is no shared secret anywhere in this system. The private key lives in the
secure element of the user's device and never leaves it; the server holds only
a public key. That removes an entire class of failure at once: nothing to
brute-force, nothing to leak from config, nothing to reuse from another breach,
and nothing phishable, because the credential is cryptographically bound to the
origin `sllm.visceral.systems` and a lookalike domain cannot elicit a usable
assertion.

`user_verification=REQUIRED`, so possession of an unlocked device is not
enough -- the authenticator must verify the human by biometric or PIN.

## The bootstrap problem, and why enrolment needs SSH

The first passkey cannot be authorised by a passkey. Enrolment is therefore
gated on a one-time token generated by scripts/enrol_passkey.py, which runs on
the Pi. The proof of authority is that you can get a shell on the box. Tokens
are single-use and expire in ENROL_TTL_S.

That also makes SSH the recovery path: lose every registered device and you
enrol a new one from a shell. Register at least two devices so this stays a
theoretical concern.

## Sessions are bearer tokens in memory, not cookies

A cookie is attached by the browser to every request to this origin, which is
what makes CSRF possible. An Authorization header must be set by script, and
cross-origin script cannot set it, so CSRF is structurally impossible rather
than merely mitigated. The cost is that a page refresh logs you out. For a
control that puts light into a chamber, being logged out too often is the
correct direction to fail in.

Not localStorage either: that survives the tab and is readable by any XSS on
the page. In memory, an injected script has to be running while the session is
live rather than harvesting a token later.

## Everything here requires HTTPS

Checked via X-Forwarded-Proto. WebAuthn itself refuses to run on an insecure
origin, but the session token that comes out of it would still cross the
network in the clear over port 80. Requests from localhost are exempt so the
box can test itself.
"""

import functools
import ipaddress
import json
import os
import pathlib
import secrets
import subprocess
import time

from flask import Blueprint, jsonify, request

admin = Blueprint('admin', __name__, url_prefix='/api/admin')

# The only unit this may touch, and the only verbs it may use. Both are fixed
# strings compared against a whitelist -- nothing from a request is ever
# interpolated into a command, and subprocess is called with an argv list so
# there is no shell to inject into.
UNIT = 'sllm-loop.service'
ACTIONS = ('start', 'stop')
SYSTEMCTL = '/usr/bin/systemctl'

TOKEN_TTL_S = 3600       # a session lasts an hour
CHALLENGE_TTL_S = 300    # a WebAuthn challenge is short-lived and single use
ENROL_TTL_S = 600        # an enrolment token lasts ten minutes

_tokens = {}       # session token -> expiry (monotonic)
_challenges = {}   # challenge id -> (challenge bytes, expiry, kind)


def _now():
    return time.monotonic()


def _is_local(addr):
    try:
        return ipaddress.ip_address(addr).is_loopback
    except ValueError:
        return False


def _client_ip():
    """The real client, for logs. remote_addr is always nginx."""
    return request.headers.get('X-Real-IP') or request.remote_addr or '?'


def _secure_transport():
    """Did this request reach the *browser* over TLS?

    Subtle, and I got it wrong once: behind nginx `request.remote_addr` is
    always 127.0.0.1, so exempting loopback exempted every request on earth and
    silently disabled this check. The proxy chain is
    browser -> TLS -> upstream proxy -> Tailscale -> nginx -> here, and the only
    honest signal is the X-Forwarded-Proto that nginx synthesises from the
    trusted-proxy map.

    An absent header means the request never went through nginx at all. The app
    binds 127.0.0.1, so that can only be something already on this box.
    """
    forwarded = request.headers.get('X-Forwarded-Proto', '').lower()
    if forwarded:
        return forwarded == 'https'
    return _is_local(request.remote_addr or '')


def _sweep():
    now = _now()
    for token, expiry in list(_tokens.items()):
        if expiry <= now:
            del _tokens[token]
    for key, (_, expiry, _kind) in list(_challenges.items()):
        if expiry <= now:
            del _challenges[key]


# --- credential store -------------------------------------------------------
# A JSON file, not a database. There are at most a handful of credentials and
# they change roughly never. It lives under data/ so it is outside the git tree.

class CredentialStore:
    def __init__(self, path):
        self.path = pathlib.Path(path)

    def _read(self):
        if not self.path.exists():
            return {"credentials": [], "enrolments": []}
        try:
            return json.loads(self.path.read_text())
        except (OSError, ValueError):
            return {"credentials": [], "enrolments": []}

    def _write(self, data):
        self.path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.path.with_suffix('.tmp')
        tmp.write_text(json.dumps(data, indent=2))
        os.chmod(tmp, 0o600)
        tmp.replace(self.path)

    def credentials(self):
        return self._read().get("credentials", [])

    def has_any(self):
        return bool(self.credentials())

    def add_credential(self, credential_id, public_key, sign_count, label):
        data = self._read()
        data.setdefault("credentials", []).append({
            "id": credential_id,
            "public_key": public_key,
            "sign_count": sign_count,
            "label": label,
            "added": time.time(),
        })
        self._write(data)

    def update_sign_count(self, credential_id, sign_count):
        data = self._read()
        for cred in data.get("credentials", []):
            if cred["id"] == credential_id:
                cred["sign_count"] = sign_count
        self._write(data)

    # --- one-time enrolment tokens -----------------------------------------

    def add_enrolment(self, token_hash, expires_at, label):
        data = self._read()
        data.setdefault("enrolments", []).append({
            "hash": token_hash,
            "expires_at": expires_at,
            "label": label,
        })
        self._write(data)

    def take_enrolment(self, token):
        """Consume a valid enrolment token. Single use, by construction."""
        import hashlib

        digest = hashlib.sha256(token.encode()).hexdigest()
        data = self._read()
        now = time.time()
        kept, found = [], None
        for entry in data.get("enrolments", []):
            if entry["expires_at"] <= now:
                continue  # expired, drop it
            if found is None and secrets.compare_digest(entry["hash"], digest):
                found = entry
                continue  # consumed, do not keep
            kept.append(entry)
        data["enrolments"] = kept
        self._write(data)
        return found


# --- session tokens ---------------------------------------------------------

def _issue_token():
    token = secrets.token_urlsafe(32)
    _tokens[token] = _now() + TOKEN_TTL_S
    return token


def _valid_token(presented):
    if not presented:
        return False
    now = _now()
    for token, expiry in list(_tokens.items()):
        if secrets.compare_digest(token, presented):
            if expiry <= now:
                del _tokens[token]
                return False
            return True
    return False


def _bearer():
    header = request.headers.get('Authorization', '')
    prefix = 'Bearer '
    return header[len(prefix):] if header.startswith(prefix) else ''


def _stash_challenge(challenge, kind):
    key = secrets.token_urlsafe(16)
    _challenges[key] = (challenge, _now() + CHALLENGE_TTL_S, kind)
    return key


def _take_challenge(key, kind):
    """Single use: a replayed challenge must not verify twice."""
    entry = _challenges.pop(key, None)
    if entry is None:
        return None
    challenge, expiry, stored_kind = entry
    if expiry <= _now() or stored_kind != kind:
        return None
    return challenge


def loop_state():
    """(active, raw). `is-active` needs no privilege."""
    try:
        result = subprocess.run(
            [SYSTEMCTL, 'is-active', UNIT],
            capture_output=True, text=True, timeout=10,
        )
        raw = (result.stdout or result.stderr).strip()
        return raw == 'active', raw
    except (OSError, subprocess.SubprocessError) as exc:
        return False, f"unknown: {exc}"


def register(app, config):
    """Attach the admin blueprint. Safe when no passkey is enrolled yet."""
    import base64

    from webauthn import (
        generate_authentication_options,
        generate_registration_options,
        options_to_json,
        verify_authentication_response,
        verify_registration_response,
    )
    from webauthn.helpers.structs import (
        AuthenticatorSelectionCriteria,
        PublicKeyCredentialDescriptor,
        ResidentKeyRequirement,
        UserVerificationRequirement,
    )

    rp_id = getattr(config, 'ADMIN_RP_ID', 'sllm.visceral.systems')
    rp_name = getattr(config, 'ADMIN_RP_NAME', 'sLLM')
    origin = getattr(config, 'ADMIN_ORIGIN', f'https://{rp_id}')
    store = CredentialStore(
        getattr(config, 'ADMIN_CREDENTIALS_FILE',
                pathlib.Path(config.DATA_DIR) / 'admin_credentials.json')
    )

    def _b64(raw):
        return base64.urlsafe_b64encode(raw).decode().rstrip('=')

    def _unb64(text):
        return base64.urlsafe_b64decode(text + '=' * (-len(text) % 4))

    def guard(view):
        @functools.wraps(view)
        def wrapped(*args, **kwargs):
            if not _secure_transport():
                return jsonify({"error": "admin requires HTTPS"}), 403
            _sweep()
            if not _valid_token(_bearer()):
                return jsonify({"error": "not authenticated"}), 401
            return view(*args, **kwargs)
        return wrapped

    # --- state ------------------------------------------------------------

    @admin.route('/state', methods=['GET'])
    def admin_state():
        """Unauthenticated: only says whether login is possible at all."""
        return jsonify({
            "enrolled": store.has_any(),
            "authenticated": _valid_token(_bearer()),
        })

    # --- enrolment --------------------------------------------------------

    @admin.route('/enrol/options', methods=['POST'])
    def enrol_options():
        if not _secure_transport():
            return jsonify({"error": "admin requires HTTPS"}), 403
        _sweep()

        token = (request.get_json(silent=True) or {}).get('enrol_token', '')
        if not isinstance(token, str) or not token:
            return jsonify({"error": "enrolment token required"}), 400
        entry = store.take_enrolment(token)
        if entry is None:
            return jsonify({"error": "invalid or expired enrolment token"}), 401

        options = generate_registration_options(
            rp_id=rp_id,
            rp_name=rp_name,
            # A stable user handle so re-registering the same device replaces
            # rather than duplicates. There is exactly one user here.
            user_id=b'sllm-admin',
            user_name='admin',
            user_display_name='sLLM admin',
            authenticator_selection=AuthenticatorSelectionCriteria(
                resident_key=ResidentKeyRequirement.PREFERRED,
                user_verification=UserVerificationRequirement.REQUIRED,
            ),
            exclude_credentials=[
                PublicKeyCredentialDescriptor(id=_unb64(cred["id"]))
                for cred in store.credentials()
            ],
        )
        key = _stash_challenge(options.challenge, 'register')
        # The consumed enrolment token is returned to the client only as an
        # opaque handle for this one flow; it is already spent server-side.
        return jsonify({
            "challenge_id": key,
            "label": entry.get("label", "passkey"),
            "options": json.loads(options_to_json(options)),
        })

    @admin.route('/enrol/verify', methods=['POST'])
    def enrol_verify():
        if not _secure_transport():
            return jsonify({"error": "admin requires HTTPS"}), 403

        body = request.get_json(silent=True) or {}
        challenge = _take_challenge(body.get('challenge_id', ''), 'register')
        if challenge is None:
            return jsonify({"error": "unknown or expired challenge"}), 400

        try:
            verification = verify_registration_response(
                credential=body.get('credential'),
                expected_challenge=challenge,
                expected_origin=origin,
                expected_rp_id=rp_id,
                require_user_verification=True,
            )
        except Exception as exc:  # noqa: BLE001 -- any failure is a rejection
            print(f"admin: passkey registration rejected: {exc}", flush=True)
            return jsonify({"error": "registration failed"}), 400

        store.add_credential(
            credential_id=_b64(verification.credential_id),
            public_key=_b64(verification.credential_public_key),
            sign_count=verification.sign_count,
            label=body.get('label') or 'passkey',
        )
        print(f"admin: passkey enrolled from {_client_ip()}", flush=True)
        return jsonify({"ok": True})

    # --- login ------------------------------------------------------------

    @admin.route('/login/options', methods=['POST'])
    def login_options():
        if not _secure_transport():
            return jsonify({"error": "admin requires HTTPS"}), 403
        _sweep()

        credentials = store.credentials()
        if not credentials:
            return jsonify({"error": "no passkey enrolled"}), 503

        options = generate_authentication_options(
            rp_id=rp_id,
            allow_credentials=[
                PublicKeyCredentialDescriptor(id=_unb64(cred["id"]))
                for cred in credentials
            ],
            user_verification=UserVerificationRequirement.REQUIRED,
        )
        key = _stash_challenge(options.challenge, 'authenticate')
        return jsonify({
            "challenge_id": key,
            "options": json.loads(options_to_json(options)),
        })

    @admin.route('/login/verify', methods=['POST'])
    def login_verify():
        if not _secure_transport():
            return jsonify({"error": "admin requires HTTPS"}), 403

        body = request.get_json(silent=True) or {}
        challenge = _take_challenge(body.get('challenge_id', ''), 'authenticate')
        if challenge is None:
            return jsonify({"error": "unknown or expired challenge"}), 400

        credential = body.get('credential') or {}
        raw_id = credential.get('rawId') or credential.get('id') or ''
        stored = next(
            (c for c in store.credentials()
             if secrets.compare_digest(c["id"], raw_id)), None
        )
        if stored is None:
            return jsonify({"error": "unknown credential"}), 401

        try:
            verification = verify_authentication_response(
                credential=credential,
                expected_challenge=challenge,
                expected_origin=origin,
                expected_rp_id=rp_id,
                credential_public_key=_unb64(stored["public_key"]),
                credential_current_sign_count=stored.get("sign_count", 0),
                require_user_verification=True,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"admin: passkey login rejected: {exc}", flush=True)
            return jsonify({"error": "authentication failed"}), 401

        # A sign count that fails to advance can indicate a cloned
        # authenticator. py_webauthn raises on a regression; persisting the new
        # value is what makes that check meaningful next time.
        store.update_sign_count(stored["id"], verification.new_sign_count)

        token = _issue_token()
        print(f"admin: login from {_client_ip()}", flush=True)
        return jsonify({"token": token, "expires_in": TOKEN_TTL_S})

    @admin.route('/logout', methods=['POST'])
    def logout():
        presented = _bearer()
        for token in list(_tokens):
            if secrets.compare_digest(token, presented):
                del _tokens[token]
        return jsonify({"ok": True})

    # --- the actual controls ----------------------------------------------

    @admin.route('/loop', methods=['GET'])
    @guard
    def loop_status():
        active, raw = loop_state()
        return jsonify({"active": active, "state": raw, "unit": UNIT})

    @admin.route('/loop', methods=['POST'])
    @guard
    def loop_control():
        action = (request.get_json(silent=True) or {}).get('action', '')
        if action not in ACTIONS:
            return jsonify({"error": f"action must be one of {list(ACTIONS)}"}), 400

        try:
            result = subprocess.run(
                ['/usr/bin/sudo', '-n', SYSTEMCTL, action, UNIT],
                capture_output=True, text=True, timeout=30,
            )
        except (OSError, subprocess.SubprocessError) as exc:
            return jsonify({"error": f"could not run systemctl: {exc}"}), 500

        if result.returncode != 0:
            detail = (result.stderr or result.stdout).strip()
            return jsonify({"error": f"systemctl {action} failed: {detail}"}), 500

        print(f"admin: {action} {UNIT} by {_client_ip()}", flush=True)
        # systemd returns before the unit settles; pause so the state reported
        # back is the one the user will actually see.
        time.sleep(1.0)
        active, raw = loop_state()
        return jsonify({"ok": True, "action": action, "active": active, "state": raw})

    app.register_blueprint(admin)
    app.config['SLLM_CREDENTIAL_STORE'] = store
    if store.has_any():
        print(f"✓ admin controls enabled ({len(store.credentials())} passkey(s))")
    else:
        print("· admin controls: no passkey enrolled "
              "(run scripts/enrol_passkey.py)")
