"""Admin controls: start and stop the model loop from the web page.

This is the one part of the API that changes what the installation is doing,
reachable from the public internet, so the threat model is written down rather
than assumed.

**What an attacker gets if this falls:** the ability to start and stop
sllm-loop. Not a shell, not the matrix directly, not the data. The polkit rule
in deploy/50-sllm-loop.rules grants the `sllm` uid exactly two verbs on exactly
one unit, so a compromise here does not escalate past toggling one service.

That started life as a sudoers rule and could not work: sllm-api.service sets
NoNewPrivileges=true and sudo is setuid, so the kernel refuses the escalation.
sudo reports this as a container misconfiguration, which is misleading -- it is
the hardening working. polkit authorises over D-Bus with no setuid binary
involved, and is narrower besides: systemd checks the unit and verb itself
rather than sudo string-matching a command line.

## Authentication is a passkey (WebAuthn), not a password

There is no shared secret anywhere in this system. The private key lives in the
secure element of the user's device and never leaves it; the server holds only
a public key. That removes an entire class of failure at once: nothing to
brute-force, nothing to leak from config, nothing to reuse from another breach,
and nothing phishable, because the credential is cryptographically bound to the
origin `sllm.visceral.systems` and a lookalike domain cannot elicit a usable
assertion.

`user_verification=REQUIRED`, so possession of an unlocked device is not
enough -- the authenticator must verify the human by biometric or PIN.

## The bootstrap problem, and why enrolment needs SSH

The first passkey cannot be authorised by a passkey. Enrolment is therefore
gated on a one-time token generated by scripts/enrol_passkey.py, which runs on
the Pi. The proof of authority is that you can get a shell on the box. Tokens
are single-use and expire in ENROL_TTL_S.

That also makes SSH the recovery path: lose every registered device and you
enrol a new one from a shell. Register at least two devices so this stays a
theoretical concern.

## Sessions are bearer tokens in memory, not cookies

A cookie is attached by the browser to every request to this origin, which is
what makes CSRF possible. An Authorization header must be set by script, and
cross-origin script cannot set it, so CSRF is structurally impossible rather
than merely mitigated. The cost is that a page refresh logs you out. For a
control that puts light into a chamber, being logged out too often is the
correct direction to fail in.

Not localStorage either: that survives the tab and is readable by any XSS on
the page. In memory, an injected script has to be running while the session is
live rather than harvesting a token later.

## Everything here requires HTTPS

Checked via X-Forwarded-Proto. WebAuthn itself refuses to run on an insecure
origin, but the session token that comes out of it would still cross the
network in the clear over port 80. Requests from localhost are exempt so the
box can test itself.
"""

import functools
import ipaddress
import json
import os
import pathlib
import secrets
import subprocess
import time

from flask import Blueprint, jsonify, request

admin = Blueprint('admin', __name__, url_prefix='/api/admin')

# The only unit this may touch, and the only verbs it may use. Both are fixed
# strings compared against a whitelist -- nothing from a request is ever
# interpolated into a command, and subprocess is called with an argv list so
# there is no shell to inject into.
# Two units, and they are mutually exclusive: both drive the same panel, so
# starting either stops the other. `demo` invents its data, and interleaving
# fabricated stimulus with a real session would leave no way to tell afterwards
# which turn caused which light.
UNITS = {
    'loop': 'sllm-loop.service',
    'demo': 'sllm-demo.service',
}
UNIT = UNITS['loop']
ACTIONS = ('start', 'stop')
SYSTEMCTL = '/usr/bin/systemctl'

TOKEN_TTL_S = 3600       # a session lasts an hour
CHALLENGE_TTL_S = 300    # a WebAuthn challenge is short-lived and single use
ENROL_TTL_S = 600        # an enrolment token lasts ten minutes

_tokens = {}       # session token -> expiry (monotonic)
_challenges = {}   # challenge id -> (challenge bytes, expiry, kind)


def _now():
    return time.monotonic()


def _is_local(addr):
    try:
        return ipaddress.ip_address(addr).is_loopback
    except ValueError:
        return False


def _client_ip():
    """The real client, for logs. remote_addr is always nginx."""
    return request.headers.get('X-Real-IP') or request.remote_addr or '?'


def _secure_transport():
    """Did this request reach the *browser* over TLS?

    Subtle, and I got it wrong once: behind nginx `request.remote_addr` is
    always 127.0.0.1, so exempting loopback exempted every request on earth and
    silently disabled this check. The proxy chain is
    browser -> TLS -> upstream proxy -> Tailscale -> nginx -> here, and the only
    honest signal is the X-Forwarded-Proto that nginx synthesises from the
    trusted-proxy map.

    An absent header means the request never went through nginx at all. The app
    binds 127.0.0.1, so that can only be something already on this box.
    """
    forwarded = request.headers.get('X-Forwarded-Proto', '').lower()
    if forwarded:
        return forwarded == 'https'
    return _is_local(request.remote_addr or '')


def _sweep():
    now = _now()
    for token, expiry in list(_tokens.items()):
        if expiry <= now:
            del _tokens[token]
    for key, (_, expiry, _kind, _payload) in list(_challenges.items()):
        if expiry <= now:
            del _challenges[key]


# --- credential store -------------------------------------------------------
# A JSON file, not a database. There are at most a handful of credentials and
# they change roughly never. It lives under data/ so it is outside the git tree.

class CredentialStore:
    def __init__(self, path):
        self.path = pathlib.Path(path)

    def _read(self):
        if not self.path.exists():
            return {"credentials": [], "enrolments": []}
        try:
            return json.loads(self.path.read_text())
        except (OSError, ValueError):
            return {"credentials": [], "enrolments": []}

    def _write(self, data):
        self.path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.path.with_suffix('.tmp')
        tmp.write_text(json.dumps(data, indent=2))
        os.chmod(tmp, 0o600)
        tmp.replace(self.path)

    def credentials(self):
        return self._read().get("credentials", [])

    def has_any(self):
        return bool(self.credentials())

    def add_credential(self, credential_id, public_key, sign_count, label):
        data = self._read()
        data.setdefault("credentials", []).append({
            "id": credential_id,
            "public_key": public_key,
            "sign_count": sign_count,
            "label": label,
            "added": time.time(),
        })
        self._write(data)

    def update_sign_count(self, credential_id, sign_count):
        data = self._read()
        for cred in data.get("credentials", []):
            if cred["id"] == credential_id:
                cred["sign_count"] = sign_count
        self._write(data)

    # --- one-time enrolment tokens -----------------------------------------

    def add_enrolment(self, token_hash, expires_at, label):
        data = self._read()
        data.setdefault("enrolments", []).append({
            "hash": token_hash,
            "expires_at": expires_at,
            "label": label,
        })
        self._write(data)

    def peek_enrolment(self, token):
        """Validate an enrolment token WITHOUT spending it.

        Registration is two round trips, and everything that can realistically
        fail -- the authenticator, the browser's credential manager, the user
        changing their mind -- fails between them. Spending the token on the
        first call means every one of those failures costs a fresh SSH session
        to mint another. It is spent in take_enrolment once a credential has
        actually been verified.
        """
        import hashlib

        digest = hashlib.sha256(token.encode()).hexdigest()
        now = time.time()
        for entry in self._read().get("enrolments", []):
            if entry["expires_at"] > now and secrets.compare_digest(entry["hash"], digest):
                return entry
        return None

    def take_enrolment(self, token):
        """Consume a valid enrolment token. Single use, by construction."""
        import hashlib

        digest = hashlib.sha256(token.encode()).hexdigest()
        data = self._read()
        now = time.time()
        kept, found = [], None
        for entry in data.get("enrolments", []):
            if entry["expires_at"] <= now:
                continue  # expired, drop it
            if found is None and secrets.compare_digest(entry["hash"], digest):
                found = entry
                continue  # consumed, do not keep
            kept.append(entry)
        data["enrolments"] = kept
        self._write(data)
        return found


# --- session tokens ---------------------------------------------------------

def _issue_token():
    token = secrets.token_urlsafe(32)
    _tokens[token] = _now() + TOKEN_TTL_S
    return token


def _valid_token(presented):
    if not presented:
        return False
    now = _now()
    for token, expiry in list(_tokens.items()):
        if secrets.compare_digest(token, presented):
            if expiry <= now:
                del _tokens[token]
                return False
            return True
    return False


def _bearer():
    header = request.headers.get('Authorization', '')
    prefix = 'Bearer '
    return header[len(prefix):] if header.startswith(prefix) else ''


def _stash_challenge(challenge, kind, payload=None):
    """`payload` carries the unspent enrolment token through registration."""
    key = secrets.token_urlsafe(16)
    _challenges[key] = (challenge, _now() + CHALLENGE_TTL_S, kind, payload)
    return key


def _take_challenge(key, kind):
    """Single use: a replayed challenge must not verify twice.

    Returns (challenge, payload), or (None, None).
    """
    entry = _challenges.pop(key, None)
    if entry is None:
        return None, None
    challenge, expiry, stored_kind, payload = entry
    if expiry <= _now() or stored_kind != kind:
        return None, None
    return challenge, payload


def is_authenticated():
    """Whether this request carries a valid admin session.

    Used by /api/turns to decide whether `sham` and `applied` are included.
    They are withheld from everyone else: the experiment depends on the model
    not knowing which turns are controls, and /logs is public.
    """
    try:
        _sweep()
        return _valid_token(_bearer())
    except Exception:  # noqa: BLE001 -- outside a request context, say no
        return False


def unit_state(unit):
    """(active, raw). `is-active` needs no privilege."""
    try:
        result = subprocess.run(
            [SYSTEMCTL, 'is-active', unit],
            capture_output=True, text=True, timeout=10,
        )
        raw = (result.stdout or result.stderr).strip()
        return raw == 'active', raw
    except (OSError, subprocess.SubprocessError) as exc:
        return False, f"unknown: {exc}"


def loop_state():
    return unit_state(UNIT)


def _systemctl(action, unit):
    """No sudo: NoNewPrivileges blocks setuid. polkit authorises the uid."""
    return subprocess.run(
        [SYSTEMCTL, action, unit],
        capture_output=True, text=True, timeout=30,
    )


def _all_states():
    return {key: dict(zip(('active', 'state'), unit_state(unit)), unit=unit)
            for key, unit in UNITS.items()}


def register(app, config):
    """Attach the admin blueprint. Safe when no passkey is enrolled yet."""
    import base64

    from webauthn import (
        generate_authentication_options,
        generate_registration_options,
        options_to_json,
        verify_authentication_response,
        verify_registration_response,
    )
    from webauthn.helpers.structs import (
        AuthenticatorSelectionCriteria,
        PublicKeyCredentialDescriptor,
        ResidentKeyRequirement,
        UserVerificationRequirement,
    )

    rp_id = getattr(config, 'ADMIN_RP_ID', 'sllm.visceral.systems')
    rp_name = getattr(config, 'ADMIN_RP_NAME', 'sLLM')
    origin = getattr(config, 'ADMIN_ORIGIN', f'https://{rp_id}')
    store = CredentialStore(
        getattr(config, 'ADMIN_CREDENTIALS_FILE',
                pathlib.Path(config.DATA_DIR) / 'admin_credentials.json')
    )

    def _b64(raw):
        return base64.urlsafe_b64encode(raw).decode().rstrip('=')

    def _unb64(text):
        return base64.urlsafe_b64decode(text + '=' * (-len(text) % 4))

    def guard(view):
        @functools.wraps(view)
        def wrapped(*args, **kwargs):
            if not _secure_transport():
                return jsonify({"error": "admin requires HTTPS"}), 403
            _sweep()
            if not _valid_token(_bearer()):
                return jsonify({"error": "not authenticated"}), 401
            return view(*args, **kwargs)
        return wrapped

    # --- state ------------------------------------------------------------

    @admin.route('/state', methods=['GET'])
    def admin_state():
        """Unauthenticated: only says whether login is possible at all."""
        return jsonify({
            "enrolled": store.has_any(),
            "authenticated": _valid_token(_bearer()),
        })

    # --- enrolment --------------------------------------------------------

    @admin.route('/enrol/options', methods=['POST'])
    def enrol_options():
        if not _secure_transport():
            return jsonify({"error": "admin requires HTTPS"}), 403
        _sweep()

        token = (request.get_json(silent=True) or {}).get('enrol_token', '')
        if not isinstance(token, str) or not token:
            return jsonify({"error": "enrolment token required"}), 400
        entry = store.peek_enrolment(token)
        if entry is None:
            return jsonify({"error": "invalid or expired enrolment token"}), 401

        options = generate_registration_options(
            rp_id=rp_id,
            rp_name=rp_name,
            # A stable user handle so re-registering the same device replaces
            # rather than duplicates. There is exactly one user here.
            user_id=b'sllm-admin',
            user_name='admin',
            user_display_name='sLLM admin',
            authenticator_selection=AuthenticatorSelectionCriteria(
                resident_key=ResidentKeyRequirement.PREFERRED,
                user_verification=UserVerificationRequirement.REQUIRED,
            ),
            # Deliberately no exclude_credentials. Its only job is to stop the
            # same authenticator being registered twice, which is harmless, and
            # Android's Credential Manager fails opaquely on it -- "an unknown
            # error occurred while talking to the credential manager", with
            # nothing reaching the server to explain it. Not worth the trade.
        )
        # The token is validated but NOT yet spent; enrol/verify spends it once
        # a credential actually verifies, so a failed attempt is retryable.
        key = _stash_challenge(options.challenge, 'register', payload=token)
        return jsonify({
            "challenge_id": key,
            "label": entry.get("label", "passkey"),
            "options": json.loads(options_to_json(options)),
        })

    @admin.route('/enrol/verify', methods=['POST'])
    def enrol_verify():
        if not _secure_transport():
            return jsonify({"error": "admin requires HTTPS"}), 403

        body = request.get_json(silent=True) or {}
        challenge, enrol_token = _take_challenge(body.get('challenge_id', ''), 'register')
        if challenge is None:
            return jsonify({"error": "unknown or expired challenge"}), 400

        try:
            verification = verify_registration_response(
                credential=body.get('credential'),
                expected_challenge=challenge,
                expected_origin=origin,
                expected_rp_id=rp_id,
                require_user_verification=True,
            )
        except Exception as exc:  # noqa: BLE001 -- any failure is a rejection
            print(f"admin: passkey registration rejected: {exc}", flush=True)
            return jsonify({"error": "registration failed"}), 400

        # Now, and only now, is the enrolment token spent.
        store.take_enrolment(enrol_token)
        store.add_credential(
            credential_id=_b64(verification.credential_id),
            public_key=_b64(verification.credential_public_key),
            sign_count=verification.sign_count,
            label=body.get('label') or 'passkey',
        )
        print(f"admin: passkey enrolled from {_client_ip()}", flush=True)
        return jsonify({"ok": True})

    # --- login ------------------------------------------------------------

    @admin.route('/login/options', methods=['POST'])
    def login_options():
        if not _secure_transport():
            return jsonify({"error": "admin requires HTTPS"}), 403
        _sweep()

        credentials = store.credentials()
        if not credentials:
            return jsonify({"error": "no passkey enrolled"}), 503

        options = generate_authentication_options(
            rp_id=rp_id,
            allow_credentials=[
                PublicKeyCredentialDescriptor(id=_unb64(cred["id"]))
                for cred in credentials
            ],
            user_verification=UserVerificationRequirement.REQUIRED,
        )
        key = _stash_challenge(options.challenge, 'authenticate')
        return jsonify({
            "challenge_id": key,
            "options": json.loads(options_to_json(options)),
        })

    @admin.route('/login/verify', methods=['POST'])
    def login_verify():
        if not _secure_transport():
            return jsonify({"error": "admin requires HTTPS"}), 403

        body = request.get_json(silent=True) or {}
        challenge, _ = _take_challenge(body.get('challenge_id', ''), 'authenticate')
        if challenge is None:
            return jsonify({"error": "unknown or expired challenge"}), 400

        credential = body.get('credential') or {}
        raw_id = credential.get('rawId') or credential.get('id') or ''
        stored = next(
            (c for c in store.credentials()
             if secrets.compare_digest(c["id"], raw_id)), None
        )
        if stored is None:
            return jsonify({"error": "unknown credential"}), 401

        try:
            verification = verify_authentication_response(
                credential=credential,
                expected_challenge=challenge,
                expected_origin=origin,
                expected_rp_id=rp_id,
                credential_public_key=_unb64(stored["public_key"]),
                credential_current_sign_count=stored.get("sign_count", 0),
                require_user_verification=True,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"admin: passkey login rejected: {exc}", flush=True)
            return jsonify({"error": "authentication failed"}), 401

        # A sign count that fails to advance can indicate a cloned
        # authenticator. py_webauthn raises on a regression; persisting the new
        # value is what makes that check meaningful next time.
        store.update_sign_count(stored["id"], verification.new_sign_count)

        token = _issue_token()
        print(f"admin: login from {_client_ip()}", flush=True)
        return jsonify({"token": token, "expires_in": TOKEN_TTL_S})

    @admin.route('/logout', methods=['POST'])
    def logout():
        presented = _bearer()
        for token in list(_tokens):
            if secrets.compare_digest(token, presented):
                del _tokens[token]
        return jsonify({"ok": True})

    # --- the actual controls ----------------------------------------------

    def _occupied_path():
        return pathlib.Path(getattr(
            config, 'CHAMBER_OCCUPIED_FILE',
            pathlib.Path(config.DATA_DIR) / 'chamber_occupied'))

    @admin.route('/chamber', methods=['GET'])
    @guard
    def chamber_status():
        return jsonify({"occupied": _occupied_path().exists()})

    @admin.route('/chamber', methods=['POST'])
    @guard
    def chamber_set():
        """Assert whether something alive is in the chamber.

        Nothing can detect this, so a human asserts it. It is stored as the
        presence of a file rather than a line in config.py: a safety flag that
        needs an SSH session and a service restart to change is one that will be
        stale exactly when it matters, and the API has no business rewriting its
        own source.
        """
        occupied = (request.get_json(silent=True) or {}).get('occupied')
        if not isinstance(occupied, bool):
            return jsonify({"error": "occupied must be true or false"}), 400

        path = _occupied_path()
        try:
            if occupied:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(
                    f"set via the admin panel at {time.time()}\n"
                    "The presence of this file means something living is in the\n"
                    "chamber. loop.py --demo refuses to run while it exists.\n")
            elif path.exists():
                path.unlink()
        except OSError as exc:
            return jsonify({"error": f"could not write the flag: {exc}"}), 500

        print(f"admin: chamber occupied={occupied} by {_client_ip()}", flush=True)
        return jsonify({"ok": True, "occupied": path.exists()})

    @admin.route('/loop', methods=['GET'])
    @guard
    def loop_status():
        states = _all_states()
        # The top-level active/state keep the original single-unit shape.
        return jsonify({**states['loop'], "units": states})

    @admin.route('/loop', methods=['POST'])
    @guard
    def loop_control():
        body = request.get_json(silent=True) or {}
        action = body.get('action', '')
        which = body.get('unit', 'loop')

        if action not in ACTIONS:
            return jsonify({"error": f"action must be one of {list(ACTIONS)}"}), 400
        if which not in UNITS:
            return jsonify({"error": f"unit must be one of {list(UNITS)}"}), 400

        unit = UNITS[which]

        try:
            # Starting either unit stops the other first. They drive the same
            # panel, and demo mode invents its data -- running both would mix
            # fabricated stimulus into a real session with no way to separate
            # them afterwards.
            if action == 'start':
                for other, other_unit in UNITS.items():
                    if other == which:
                        continue
                    running, _ = unit_state(other_unit)
                    if not running:
                        continue
                    stopped = _systemctl('stop', other_unit)
                    if stopped.returncode != 0:
                        detail = (stopped.stderr or stopped.stdout).strip()
                        return jsonify({
                            "error": f"could not stop {other_unit} first: {detail}"
                        }), 500
                    print(f"admin: stopped {other_unit} to start {unit}", flush=True)

            result = _systemctl(action, unit)
        except (OSError, subprocess.SubprocessError) as exc:
            return jsonify({"error": f"could not run systemctl: {exc}"}), 500

        if result.returncode != 0:
            detail = (result.stderr or result.stdout).strip()
            return jsonify({"error": f"systemctl {action} {which} failed: {detail}"}), 500

        print(f"admin: {action} {unit} by {_client_ip()}", flush=True)
        # systemd returns before the unit settles; pause so the state reported
        # back is the one the user will actually see.
        time.sleep(1.0)
        states = _all_states()
        return jsonify({"ok": True, "action": action, "unit": which,
                        **states[which], "units": states})

    app.register_blueprint(admin)
    app.config['SLLM_CREDENTIAL_STORE'] = store
    if store.has_any():
        print(f"✓ admin controls enabled ({len(store.credentials())} passkey(s))")
    else:
        print("· admin controls: no passkey enrolled "
              "(run scripts/enrol_passkey.py)")
